### ISSUE TITLE
Project should have a Makefile

### ISSUE THREAD

**Issue by turanoo** [caporaso-lab/SurveySync#2]
Include all the commands that need to be executed by the system.

**Comment by thermokarst** [comment]
For the initial draft of this, the commands can just be placeholders.

**Comment by thermokarst** [comment]
Some example Makefiles:

- https://github.com/qiime2/vm-playbooks/blob/master/Makefile
- https://github.com/qiime2/q2-taxa/blob/master/Makefile
- https://github.com/qiime2/docs/blob/master/Makefile

Right now, lets have the following directives:

- `make help` -> displays help text about the directives available in the Makefile.
- `make build` -> runs `npm run build`
- `make lint` -> runs `npm run lint`
- `make deploy` -> runs the commands [listed here](https://github.com/caporaso-lab/SurveySync#deploy-instructions).
- `make dev` -> runs `yarn install`

There will be some overlap with the `npm run ...` commands.
