### ISSUE TITLE
Code should have a README document

### ISSUE THREAD

**Issue by turanoo** [caporaso-lab/SurveySync#3]
The README file will help visitors learn about the Add-On and how to run it.

**Comment by thermokarst** [comment]
This should be written [in Markdown](https://guides.github.com/features/mastering-markdown/).

A good example of a typical README [can be found here](https://github.com/qiime2/vm-playbooks).

Sections to include:
- Project title
- Description of the project
- Developer Quickstart (instructions on how to install, run, etc. This will be the `make` directives in the future)

---

We will add more content and sections as we proceed with bootstrapping.
